---
name: CI

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

env:
  GEM_HOME: "$GITHUB_ACTION_PATH/.gems"
  GEM_PATH: "$GITHUB_ACTION_PATH/.gems:$GEM_PATH"

jobs:
  lint:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: '3.7.x'

      - name: setup env
        run: make circleci

      - name: shellcheck
        run: make shellcheck

      - name: lint
        run: make lint

      - name: install requirements
        run: make deps fpm package_cloud

      - name: build
        run: CIRCLECI=true make build

      - name: bash tests
        run: basht tests/**/tests.sh
